/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author Eyal Blumental Erez
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    public double calculator = 0;

    public double numberStorage = 0;

    public double numberStorageMultiply = 0;

    public double numberStorageDivide = 0;

    public String numbers = "";

    public String calculationType = "none";

    public double saveAnswer = 0;

    public boolean needDivide = false;

    public boolean needMultiply = false;

    public boolean needMinus = false;

    /**
     * *****************************************************************************************
     *
     * NEED TO TRY NEW ALGORITHM, HAVE CALCULATOR AS (X + X / X * X - X) ETC.
     * FOLLOW BEDMAS RUlES WITH VARIABLES INSIDE THE CALCULATOR DOUBLE VALUE
     * WHICH CALCULATES AFTER USER CLICKS EQUALS BUTTON
     *
     *******************************************************************************************
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonZero = new javax.swing.JButton();
        buttonFive = new javax.swing.JButton();
        buttonNine = new javax.swing.JButton();
        buttonTwo = new javax.swing.JButton();
        buttonSix = new javax.swing.JButton();
        buttonThree = new javax.swing.JButton();
        buttonEight = new javax.swing.JButton();
        buttonSeven = new javax.swing.JButton();
        buttonFour = new javax.swing.JButton();
        buttonPlus = new javax.swing.JButton();
        buttonEquals = new javax.swing.JButton();
        buttonOne1 = new javax.swing.JButton();
        calculationText = new javax.swing.JTextField();
        buttonAC = new javax.swing.JButton();
        buttonMinus = new javax.swing.JButton();
        buttonDivide = new javax.swing.JButton();
        buttonMultiply = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonZero.setText("0");
        buttonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZeroActionPerformed(evt);
            }
        });

        buttonFive.setText("5");
        buttonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiveActionPerformed(evt);
            }
        });

        buttonNine.setText("9");
        buttonNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNineActionPerformed(evt);
            }
        });

        buttonTwo.setText("2");
        buttonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTwoActionPerformed(evt);
            }
        });

        buttonSix.setText("6");
        buttonSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSixActionPerformed(evt);
            }
        });

        buttonThree.setText("3");
        buttonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThreeActionPerformed(evt);
            }
        });

        buttonEight.setText("8");
        buttonEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEightActionPerformed(evt);
            }
        });

        buttonSeven.setText("7");
        buttonSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSevenActionPerformed(evt);
            }
        });

        buttonFour.setText("4");
        buttonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFourActionPerformed(evt);
            }
        });

        buttonPlus.setText("+");
        buttonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlusActionPerformed(evt);
            }
        });

        buttonEquals.setText("=");
        buttonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEqualsActionPerformed(evt);
            }
        });

        buttonOne1.setText("1");
        buttonOne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOne1ActionPerformed(evt);
            }
        });

        calculationText.setEditable(false);
        calculationText.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        calculationText.setText("0");
        calculationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculationTextActionPerformed(evt);
            }
        });

        buttonAC.setText("AC");
        buttonAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonACActionPerformed(evt);
            }
        });

        buttonMinus.setText("-");
        buttonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMinusActionPerformed(evt);
            }
        });

        buttonDivide.setText("/");
        buttonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivideActionPerformed(evt);
            }
        });

        buttonMultiply.setText("X");
        buttonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultiplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calculationText, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonZero, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(buttonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonOne1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonSeven, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonEight, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonNine, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(85, 85, 85))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(buttonEquals, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(buttonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonAC, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(389, 389, 389))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(calculationText, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEight, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNine, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOne1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonZero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZeroActionPerformed
// need to fix clicking number twice and comes up with error and calculator value = 0 due to error
        if (calculationType == "multiply") {

            if (needMultiply == false) {

                numbers = numbers + 0;

                calculationText.setText(numbers);

                if (calculator == 0) {

                    calculator = Double.parseDouble(numbers) * numberStorage;

                } else if (calculator != 0) {

                    calculator = calculator * numberStorage;

                }

            } else if (needMultiply == true) {

                numbers = numbers + 0;

                calculator = Double.parseDouble(numbers) * calculator;

                needMultiply = false;

            }

            numberStorage = 0;

        } else if (calculationType == "divide") {

        } else if (needMinus == true && calculationType == "minus") {

            numbers = numbers + 0;

            calculator = (numberStorage + calculator) - Double.parseDouble(numbers);

            calculationText.setText(numbers);

            needMinus = false;

        } else if (calculationType == "none") {

            numbers = numbers + 0;

            calculationText.setText(numbers);

        } else {

        }
    }//GEN-LAST:event_buttonZeroActionPerformed

    private void buttonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEqualsActionPerformed

        if (calculationType == "add") {

            calculator = calculator + Double.parseDouble(numbers);

        } else if (calculationType == "minus") {

            calculator = calculator - Double.parseDouble(numbers);

        } else if (calculationType == "divide") {

            needDivide = false;

        } else if (calculationType == "multiply") {

            needMultiply = false;

        } else if (calculationType == "none") {

            if (numbers == "") {

                numbers = "0";

            }

            calculator = Double.parseDouble(numbers);

        }

        calculationText.setText(Double.toString(calculator));

        numberStorage = 0;

        numbers = "0";

        calculationType = "none";

    }//GEN-LAST:event_buttonEqualsActionPerformed

    private void buttonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTwoActionPerformed
        if (calculationType == "multiply") {

            if (needMultiply == false) {

                numbers = numbers + 2;

                calculationText.setText(numbers);

                if (calculator == 0) {

                    calculator = Double.parseDouble(numbers) * numberStorage;

                } else if (calculator != 0) {

                    calculator = calculator * numberStorage;

                }

            } else if (needMultiply == true) {

                numbers = numbers + 2;

                calculator = Double.parseDouble(numbers) * calculator;

                needMultiply = false;

            }

            numberStorage = 0;

        } else if (calculationType == "divide") { // divide not working need to fix

        } else if (needMinus == true && calculationType == "minus") {

            numbers = numbers + 2;

            calculator = (numberStorage + calculator) - Double.parseDouble(numbers);

            calculationText.setText(numbers);

            needMinus = false;

        } else if (calculationType == "minus" && needMinus == false) {

            numbers = numbers + 2; // need to fix

            calculationText.setText(numbers);

        } else {

            numbers = numbers + 2;

            calculationText.setText(numbers);

            numberStorage = 0;

        }
    }//GEN-LAST:event_buttonTwoActionPerformed

    private void buttonOne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOne1ActionPerformed

        if (calculationType == "multiply") {

            if (needMultiply == false) {

                numbers = numbers + 1;

                calculationText.setText(numbers);

                if (calculator == 0) {

                    calculator = Double.parseDouble(numbers) * numberStorage;

                } else if (calculator != 0) {

                    calculator = calculator * numberStorage;

                }

            } else if (needMultiply == true) {

                numbers = numbers + 1;

                calculator = Double.parseDouble(numbers) * calculator;

                needMultiply = false;

            }

            numberStorage = 0;

        } else if (calculationType == "divide") {

        } else if (needMinus == true) {

            numbers = numbers + 1;

            calculator = numberStorage - Double.parseDouble(numbers);

            calculationText.setText(numbers);

            needMinus = false;

        } else {

            numbers = numbers + 1;

            calculationText.setText(numbers);

        }
    }//GEN-LAST:event_buttonOne1ActionPerformed

    private void buttonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThreeActionPerformed

        if (calculationType == "multiply") {

            if (needMultiply == false) {

                numbers = numbers + 3;

                calculationText.setText(numbers);

                if (calculator == 0) {

                    calculator = Double.parseDouble(numbers) * numberStorage;

                } else if (calculator != 0) {

                    calculator = calculator * numberStorage;

                }

            } else if (needMultiply == true) {

                numbers = numbers + 3;

                calculator = Double.parseDouble(numbers) * calculator;

                needMultiply = false;

            }

            numberStorage = 0;

        } else if (calculationType == "divide") {

        } else if (needMinus == true) {

            numbers = numbers + 3;

            calculator = numberStorage - Double.parseDouble(numbers);

            calculationText.setText(numbers);

            needMinus = false;

        } else {

            numbers = numbers + 3;

            calculationText.setText(numbers);

        }
    }//GEN-LAST:event_buttonThreeActionPerformed

    private void buttonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFourActionPerformed

        if (calculationType == "multiply") {

            if (needMultiply == false) {

                numbers = numbers + 4;

                calculationText.setText(numbers);

                if (calculator == 0) {

                    calculator = Double.parseDouble(numbers) * numberStorage;

                } else if (calculator != 0) {

                    calculator = calculator * numberStorage;

                }

            } else if (needMultiply == true) {

                numbers = numbers + 4;

                calculator = Double.parseDouble(numbers) * calculator;

                needMultiply = false;

            }

            numberStorage = 0;

        } else if (calculationType == "divide") {

        } else if (needMinus == true) {

            numbers = numbers + 4;

            calculator = numberStorage - Double.parseDouble(numbers);

            calculationText.setText(numbers);

            needMinus = false;

        } else {

            numbers = numbers + 4;

            calculationText.setText(numbers);

        }
    }//GEN-LAST:event_buttonFourActionPerformed

    private void buttonFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFiveActionPerformed

        if (calculationType == "multiply") {

            if (needMultiply == false) {

                numbers = numbers + 5;

                calculationText.setText(numbers);

                if (calculator == 0) {

                    calculator = Double.parseDouble(numbers) * numberStorage;

                } else if (calculator != 0) {

                    calculator = calculator * numberStorage;

                }

            } else if (needMultiply == true) {

                numbers = numbers + 5;

                calculator = Double.parseDouble(numbers) * calculator;

                needMultiply = false;

            }

            numberStorage = 0;

        } else if (calculationType == "divide") {

        } else if (needMinus == true) {

            numbers = numbers + 5;

            calculator = numberStorage - Double.parseDouble(numbers);

            calculationText.setText(numbers);

            needMinus = false;

        } else {

            numbers = numbers + 5;

            calculationText.setText(numbers);

        }

    }//GEN-LAST:event_buttonFiveActionPerformed

    private void buttonSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSixActionPerformed

        if (calculationType == "multiply") {

            if (needMultiply == false) {

                numbers = numbers + 6;

                calculationText.setText(numbers);

                if (calculator == 0) {

                    calculator = Double.parseDouble(numbers) * numberStorage;

                    needMultiply = false;

                } else if (calculator != 0) {

                    calculator = calculator * numberStorage;

                }

            } else if (needMultiply == true) {

                numbers = numbers + 6;

                calculator = Double.parseDouble(numbers) * calculator;

                needMultiply = false;

            }

            numberStorage = 0;

        } else if (calculationType == "divide") {

        } else if (needMinus == true) {

            numbers = numbers + 6;

            calculator = numberStorage - Double.parseDouble(numbers);

            calculationText.setText(numbers);

            needMinus = false;

        } else {

            numbers = numbers + 6;

            calculationText.setText(numbers);

        }
    }//GEN-LAST:event_buttonSixActionPerformed

    private void buttonSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSevenActionPerformed

        if (calculationType == "multiply") {

            if (needMultiply == false) {

                numbers = numbers + 7;

                calculationText.setText(numbers);

                if (calculator == 0) {

                    calculator = Double.parseDouble(numbers) * numberStorage;

                } else if (calculator != 0) {

                    calculator = calculator * numberStorage;

                }

            } else if (needMultiply == true) {

                numbers = numbers + 7;

                calculator = Double.parseDouble(numbers) * calculator;

                needMultiply = false;

            }

            numberStorage = 0;

        } else if (calculationType == "divide") {

        } else if (needMinus == true) {

            numbers = numbers + 7;

            calculator = numberStorage - Double.parseDouble(numbers);

            calculationText.setText(numbers);

            needMinus = false;

        } else {

            numbers = numbers + 7;

            calculationText.setText(numbers);

        }
    }//GEN-LAST:event_buttonSevenActionPerformed

    private void buttonEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEightActionPerformed

        if (calculationType == "multiply") {

            if (needMultiply == false) {

                numbers = numbers + 8;

                calculationText.setText(numbers);

                if (calculator == 0) {

                    calculator = Double.parseDouble(numbers) * numberStorage;

                } else if (calculator != 0) {

                    calculator = calculator * numberStorage;

                }

            } else if (needMultiply == true) {

                numbers = numbers + 8;

                calculator = Double.parseDouble(numbers) * calculator;

                needMultiply = false;

            }

            numberStorage = 0;

        } else if (calculationType == "divide") {

        } else if (needMinus == true) {

            numbers = numbers + 8;

            calculator = numberStorage - Double.parseDouble(numbers);

            calculationText.setText(numbers);

            needMinus = false;

        } else {

            numbers = numbers + 8;

            calculationText.setText(numbers);

        }
    }//GEN-LAST:event_buttonEightActionPerformed

    private void buttonNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNineActionPerformed

        if (calculationType == "multiply") {

            if (needMultiply == false) {

                numbers = numbers + 9;

                calculationText.setText(numbers);

                if (calculator == 0) {

                    calculator = Double.parseDouble(numbers) * numberStorage;

                } else if (calculator != 0) {

                    calculator = calculator * numberStorage;

                }

            } else if (needMultiply == true) {

                numbers = numbers + 9;

                calculator = Double.parseDouble(numbers) * calculator;

            }

            numberStorage = 0;

        } else if (calculationType == "divide") {

        } else if (needMinus == true) {

            numbers = numbers + 9;

            calculator = numberStorage - Double.parseDouble(numbers);

            calculationText.setText(numbers);

            needMinus = false;

        } else {

            numbers = numbers + 9;

            calculationText.setText(numbers);

        }
    }//GEN-LAST:event_buttonNineActionPerformed

    private void buttonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlusActionPerformed

        calculationType = "add";

        numberStorage = Double.parseDouble(numbers);

        numbers = "";

        calculator = numberStorage + calculator;

        numberStorage = 0;
    }//GEN-LAST:event_buttonPlusActionPerformed

    private void calculationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculationTextActionPerformed

    }//GEN-LAST:event_calculationTextActionPerformed

    private void buttonACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonACActionPerformed

        numbers = "";

        calculationType = "none";

        calculator = 0;

        numberStorage = 0;

        calculationText.setText("0");

    }//GEN-LAST:event_buttonACActionPerformed

    private void buttonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMinusActionPerformed

        if (calculator == 0) { //need to fix

            numberStorage = Double.parseDouble(numbers);

            numbers = "";

            needMinus = true;

        } else if (needMinus == false && calculationType == "minus") {

            calculator = numberStorage - Double.parseDouble(numbers);

        } else {

            numberStorage = Double.parseDouble(numbers);

            numbers = "";

            calculator = calculator - numberStorage;

            calculationType = "minus";

        }

        numberStorage = 0;
    }//GEN-LAST:event_buttonMinusActionPerformed

    private void buttonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivideActionPerformed

        //    calculationType = "divide";
        //   needDivide = true;
        //   if (calculator == 0 && numberStorage == 0) {
        //      numberStorage = Double.parseDouble(numbers);
        //   } else if (numberStorage != 0) {
        //      calculator = calculator / numberStorage;
        //   }
        //   numbers = "";
        //    numberStorage = 0;

    }//GEN-LAST:event_buttonDivideActionPerformed

    private void buttonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultiplyActionPerformed

        calculationType = "multiply";

        if (calculator != 0) {

            needMultiply = true;

        } else {

            numberStorage = Double.parseDouble(numbers);

        }

        numbers = "";
    }//GEN-LAST:event_buttonMultiplyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAC;
    private javax.swing.JButton buttonDivide;
    private javax.swing.JButton buttonEight;
    private javax.swing.JButton buttonEquals;
    private javax.swing.JButton buttonFive;
    private javax.swing.JButton buttonFour;
    private javax.swing.JButton buttonMinus;
    private javax.swing.JButton buttonMultiply;
    private javax.swing.JButton buttonNine;
    private javax.swing.JButton buttonOne1;
    private javax.swing.JButton buttonPlus;
    private javax.swing.JButton buttonSeven;
    private javax.swing.JButton buttonSix;
    private javax.swing.JButton buttonThree;
    private javax.swing.JButton buttonTwo;
    private javax.swing.JButton buttonZero;
    private javax.swing.JTextField calculationText;
    // End of variables declaration//GEN-END:variables
}
