/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package languagetranslator;

import java.util.*;
import java.io.*;

/**
 *
 * @author Eyal Blumental Erez
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtonGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTranslate = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputTranslate = new javax.swing.JTextArea();
        translatorTitle = new javax.swing.JLabel();
        subTitleInput = new javax.swing.JLabel();
        subTitleOutput = new javax.swing.JLabel();
        translateButton = new javax.swing.JButton();
        radioButtonEnglish = new javax.swing.JRadioButton();
        radioButtonMaori = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        outputTranslate.setColumns(20);
        outputTranslate.setRows(3);
        jScrollPane1.setViewportView(outputTranslate);

        inputTranslate.setColumns(20);
        inputTranslate.setRows(3);
        jScrollPane2.setViewportView(inputTranslate);

        translatorTitle.setFont(new java.awt.Font("MingLiU-ExtB", 1, 18)); // NOI18N
        translatorTitle.setText("The Mighty Translator");

        subTitleInput.setText("Insert English Or Maori Sententences Here");

        subTitleOutput.setText("Translated Text");

        translateButton.setText("Translate");
        translateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                translateButtonActionPerformed(evt);
            }
        });

        radioButtonGroup.add(radioButtonEnglish);
        radioButtonEnglish.setSelected(true);
        radioButtonEnglish.setText("English to Maori");
        radioButtonEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonEnglishActionPerformed(evt);
            }
        });

        radioButtonGroup.add(radioButtonMaori);
        radioButtonMaori.setText("Maori to English");
        radioButtonMaori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonMaoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(subTitleInput)
                .addGap(200, 200, 200))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(translatorTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioButtonEnglish)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioButtonMaori)
                                .addGap(112, 112, 112)
                                .addComponent(translateButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(subTitleOutput)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(translatorTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonEnglish)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(translateButton)
                    .addComponent(radioButtonMaori))
                .addGap(47, 47, 47)
                .addComponent(subTitleInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(subTitleOutput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * When the translate button this void method is called, this starts the
     * translation operation by getting whats in the input box and sends it into
     * the reader method in the LanguageTranslator file to start the translation
     * process.
     */
    private void translateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_translateButtonActionPerformed

        String words = "";

        String whatsThere = inputTranslate.getText();

        // this sends the whatsThere string into the reader in the other file which spits up the words and puts them into the arrayList
        LanguageTranslator.Reader(whatsThere);

        whatsThere = "";

        outputTranslate.setText("");

        /** this for loop takes the split words in the "splitWords" arrayList and writes it into the output text box for the user to read.
         * this also checks if there is punctuation in the next word to know if it is needed to add a space or not.
         */
        for (int i = 0; i < LanguageTranslator.splitWords.size(); i++) {

            whatsThere = outputTranslate.getText();

            try {

                String needToPrint = LanguageTranslator.splitWords.get(i + 1);

                System.out.println(needToPrint);

                if (Arrays.asList(LanguageTranslator.PUNCTUATION).contains(needToPrint)) {

                    words = words + whatsThere + LanguageTranslator.splitWords.get(i);

                } else {

                    words = words + whatsThere + LanguageTranslator.splitWords.get(i) + " ";
                }

            } catch (StringIndexOutOfBoundsException ex) {

            } catch (IndexOutOfBoundsException ex) {

            }

        }
        outputTranslate.setText(words.trim());
    }//GEN-LAST:event_translateButtonActionPerformed
// When the english to maori radio button this is clicked this method is called
    private void radioButtonEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonEnglishActionPerformed
        LanguageTranslator.languageOption = "ENGLISH";
    }//GEN-LAST:event_radioButtonEnglishActionPerformed
// When the maori to english radio button is clicked this method is called
    private void radioButtonMaoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonMaoriActionPerformed
        LanguageTranslator.languageOption = "MAORI";
    }//GEN-LAST:event_radioButtonMaoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea inputTranslate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea outputTranslate;
    private javax.swing.JRadioButton radioButtonEnglish;
    private javax.swing.ButtonGroup radioButtonGroup;
    private javax.swing.JRadioButton radioButtonMaori;
    private javax.swing.JLabel subTitleInput;
    private javax.swing.JLabel subTitleOutput;
    private javax.swing.JButton translateButton;
    private javax.swing.JLabel translatorTitle;
    // End of variables declaration//GEN-END:variables

}
